server:
  port: 11000

spring:
  datasource:
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall_wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password:
  application:
    name: gulimall-ware
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/**/*.xml

